### ISSUE TITLE
"Noisy" containers lead to uncaught exception 

### ISSUE THREAD

**Issue by nblei** [illinois-cs241/broadway-api#70]
I've been having one of our pipeline stages print the stdout of ModelSim, so our nohup files will have a recording of the exact output of their simulation run (completely not necessary, so I'll remove it), but this seems to be causing an unhandled error for Mongo

<details>
<summary>Relevant Logs:</summary>

```
ERROR:tornado.application:Uncaught exception POST /api/v1/grading_job/grader2
HTTPServerRequest(protocol='http', host='xxx.xxx.xxx.xxx:1470', method='POST', uri='/api/v1/grading_job/grader2', version='HTTP/1.1', remote_ip='xxx.xxx.xxx.xxx')
Traceback (most recent call last):
 File "/home/nbleier3/.local/lib/python3.5/site-packages/tornado/web.py", line 1592, in _execute
   result = yield result
 File "/home/nbleier3/.local/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
   value = future.result()
 File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
   raise self._exception
 File "/home/nbleier3/.local/lib/python3.5/site-packages/tornado/gen.py", line 326, in wrapper
   yielded = next(result)
 File "/home/nbleier3/.local/lib/python3.5/site-packages/tornado_json/schema.py", line 160, in _wrapper
   output = rh_method(self, *args, **kwargs)
 File "/home/nbleier3/broadway-api/broadway_api/handlers/worker.py", line 178, in post
   job_log_dao.insert(job_log)
 File "/home/nbleier3/broadway-api/broadway_api/daos/grading_job_log.py", line 23, in insert
   return self._collection.insert_one(document)
 File "/home/nbleier3/.local/lib/python3.5/site-packages/pymongo/collection.py", line 693, in insert_one
   session=session),
 File "/home/nbleier3/.local/lib/python3.5/site-packages/pymongo/collection.py", line 607, in _insert
   bypass_doc_val, session)
 File "/home/nbleier3/.local/lib/python3.5/site-packages/pymongo/collection.py", line 595, in _insert_one
   acknowledged, _insert_command, session)
 File "/home/nbleier3/.local/lib/python3.5/site-packages/pymongo/mongo_client.py", line 1248, in _retryable_write
   return self._retry_with_session(retryable, func, s, None)
 File "/home/nbleier3/.local/lib/python3.5/site-packages/pymongo/mongo_client.py", line 1201, in _retry_with_session
   return func(session, sock_info, retryable)
 File "/home/nbleier3/.local/lib/python3.5/site-packages/pymongo/collection.py", line 590, in _insert_command
   retryable_write=retryable_write)
 File "/home/nbleier3/.local/lib/python3.5/site-packages/pymongo/pool.py", line 584, in command
   self._raise_connection_failure(error)
 File "/home/nbleier3/.local/lib/python3.5/site-packages/pymongo/pool.py", line 745, in _raise_connection_failure
   raise error
 File "/home/nbleier3/.local/lib/python3.5/site-packages/pymongo/pool.py", line 579, in command
   unacknowledged=unacknowledged)
 File "/home/nbleier3/.local/lib/python3.5/site-packages/pymongo/network.py", line 128, in command
   name, size, max_bson_size + message._COMMAND_OVERHEAD)
 File "/home/nbleier3/.local/lib/python3.5/site-packages/pymongo/message.py", line 961, in _raise_document_too_large
   " bytes." % (doc_size, max_size))
pymongo.errors.DocumentTooLarge: BSON document too large (42553799 bytes) - the connected server supports BSON document sizes up to 16793598 bytes.
```

</details>

This isn't crashing the API, nor is it crashing Mongo, but it does appear to terminate the entire grading run.

Suggested fixes include adding a config option to disable logging to MongoDB and, in the case that logging is activated but the output is too large, to catch the exception, print some type of warning, and continue the grading run

**Comment by ayushr2** [comment]
Yes as @nblei mentioned the two possible solutions we are looking at are:
- Adding a new optional field here in the [grading stage](https://github.com/illinois-cs241/broadway-api/wiki/Configs#grading-stage-config) called `logs` which is true by default. When set to false, the Broadway grader would discard the logs generated.
- MongoDB has a limit of 4MB (old versions) and 16MB (newest version) of document size. We could calculate log size on the broadway grader and if it is above 4MB, we save logs as:
```
{
    "stdout": "",
    "stderr": "Logs not saved because it was more than 4MB",
}
```

My concern with the second solution is that it is very Mongo specific while we have made an attempt to create a DAO layer so people could plug in other databases. #29 

Thoughts @nmagerko @rod-lin @bhuvy2

**Comment by jasonB221** [comment]
WRT your second point, could you not add the validation to the DAO itself, so each DAO can decide whether or not it wants to continue execution or error out if the size is too large?

**Comment by nmagerko** [comment]
Truncation and/or validation in the DAO seems like the way to go for extreme cases, but having a `logs` option in the grading stage sounds like a very reasonable thing to have as well.
